// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void OUT1_ON(lv_event_t * e);
void OUT1_OFF(lv_event_t * e);
void OUT3_ON(lv_event_t * e);
void OUT3_OFF(lv_event_t * e);
void OUT2_ON(lv_event_t * e);
void OUT2_OFF(lv_event_t * e);
void OUT4_ON(lv_event_t * e);
void OUT4_OFF(lv_event_t * e);
void button1_on(lv_event_t * e);
void button1_off(lv_event_t * e);
void button3_on(lv_event_t * e);
void button3_off(lv_event_t * e);
void button2_on(lv_event_t * e);
void button2_off(lv_event_t * e);
void button4_on(lv_event_t * e);
void button4_off(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
