// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_DIGI_PANEL;
lv_obj_t * ui_DIGI_MAIN_LABEL;
lv_obj_t * ui_DIGI1;
lv_obj_t * ui_digi1;
lv_obj_t * ui_Dvalue1;
lv_obj_t * ui_DIGI2;
lv_obj_t * ui_digi2;
lv_obj_t * ui_Dvalue2;
lv_obj_t * ui_DIGI3;
lv_obj_t * ui_digi3;
lv_obj_t * ui_Dvalue3;
lv_obj_t * ui_DIGI4;
lv_obj_t * ui_digi4;
lv_obj_t * ui_Dvalue4;
lv_obj_t * ui_ANA_PANEL;
lv_obj_t * ui_ANA_MAIN_LABEL;
lv_obj_t * ui_ANA1;
lv_obj_t * ui_ana1;
lv_obj_t * ui_Avalue1;
lv_obj_t * ui_ANA2;
lv_obj_t * ui_ana2;
lv_obj_t * ui_Avalue2;
lv_obj_t * ui_ANA3;
lv_obj_t * ui_Avalue3;
lv_obj_t * ui_ana3;
lv_obj_t * ui_ANA4;
lv_obj_t * ui_ana4;
lv_obj_t * ui_Avalue4;
lv_obj_t * ui_INPUT_LABEL;
void ui_event_NEXT1(lv_event_t * e);
lv_obj_t * ui_NEXT1;
lv_obj_t * ui_NEXT2;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_OUTPUT_LABEL;
lv_obj_t * ui_OUT1;
void ui_event_ON1(lv_event_t * e);
lv_obj_t * ui_ON1;
lv_obj_t * ui_on1test;
void ui_event_OFF1(lv_event_t * e);
lv_obj_t * ui_OFF1;
lv_obj_t * ui_off1test;
lv_obj_t * ui_out1;
lv_obj_t * ui_OUT3;
lv_obj_t * ui_out3;
void ui_event_ON3(lv_event_t * e);
lv_obj_t * ui_ON3;
lv_obj_t * ui_on3test;
void ui_event_OFF3(lv_event_t * e);
lv_obj_t * ui_OFF3;
lv_obj_t * ui_off3test;
lv_obj_t * ui_OUT2;
lv_obj_t * ui_out2;
void ui_event_ON2(lv_event_t * e);
lv_obj_t * ui_ON2;
lv_obj_t * ui_on2test;
void ui_event_OFF2(lv_event_t * e);
lv_obj_t * ui_OFF2;
lv_obj_t * ui_off2test;
lv_obj_t * ui_OUT4;
lv_obj_t * ui_out4;
void ui_event_ON4(lv_event_t * e);
lv_obj_t * ui_ON4;
lv_obj_t * ui_on4test;
void ui_event_OFF4(lv_event_t * e);
lv_obj_t * ui_OFF4;
lv_obj_t * ui_off4test;
void ui_event_PREVIOUS1(lv_event_t * e);
lv_obj_t * ui_PREVIOUS1;
lv_obj_t * ui_PREVIOUS2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_NEXT1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_ON1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OUT1_ON(e);
    }
}
void ui_event_OFF1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OUT1_OFF(e);
    }
}
void ui_event_ON3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OUT3_ON(e);
    }
}
void ui_event_OFF3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OUT3_OFF(e);
    }
}
void ui_event_ON2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OUT2_ON(e);
    }
}
void ui_event_OFF2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OUT2_OFF(e);
    }
}
void ui_event_ON4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OUT4_ON(e);
    }
}
void ui_event_OFF4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OUT4_OFF(e);
    }
}
void ui_event_PREVIOUS1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
