// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project1

#ifndef _SQUARELINE_PROJECT1_UI_H
#define _SQUARELINE_PROJECT1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_DIGI_PANEL;
extern lv_obj_t * ui_DIGI_MAIN_LABEL;
extern lv_obj_t * ui_DIGI1;
extern lv_obj_t * ui_digi1;
extern lv_obj_t * ui_Dvalue1;
extern lv_obj_t * ui_DIGI2;
extern lv_obj_t * ui_digi2;
extern lv_obj_t * ui_Dvalue2;
extern lv_obj_t * ui_DIGI3;
extern lv_obj_t * ui_digi3;
extern lv_obj_t * ui_Dvalue3;
extern lv_obj_t * ui_DIGI4;
extern lv_obj_t * ui_digi4;
extern lv_obj_t * ui_Dvalue4;
extern lv_obj_t * ui_ANA_PANEL;
extern lv_obj_t * ui_ANA_MAIN_LABEL;
extern lv_obj_t * ui_ANA1;
extern lv_obj_t * ui_ana1;
extern lv_obj_t * ui_Avalue1;
extern lv_obj_t * ui_ANA2;
extern lv_obj_t * ui_ana2;
extern lv_obj_t * ui_Avalue2;
extern lv_obj_t * ui_ANA3;
extern lv_obj_t * ui_Avalue3;
extern lv_obj_t * ui_ana3;
extern lv_obj_t * ui_ANA4;
extern lv_obj_t * ui_ana4;
extern lv_obj_t * ui_Avalue4;
extern lv_obj_t * ui_INPUT_LABEL;
void ui_event_NEXT1(lv_event_t * e);
extern lv_obj_t * ui_NEXT1;
extern lv_obj_t * ui_NEXT2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_OUTPUT_LABEL;
extern lv_obj_t * ui_OUT1;
void ui_event_ON1(lv_event_t * e);
extern lv_obj_t * ui_ON1;
extern lv_obj_t * ui_on1test;
void ui_event_OFF1(lv_event_t * e);
extern lv_obj_t * ui_OFF1;
extern lv_obj_t * ui_off1test;
extern lv_obj_t * ui_out1;
extern lv_obj_t * ui_OUT3;
extern lv_obj_t * ui_out3;
void ui_event_ON3(lv_event_t * e);
extern lv_obj_t * ui_ON3;
extern lv_obj_t * ui_on3test;
void ui_event_OFF3(lv_event_t * e);
extern lv_obj_t * ui_OFF3;
extern lv_obj_t * ui_off3test;
extern lv_obj_t * ui_OUT2;
extern lv_obj_t * ui_out2;
void ui_event_ON2(lv_event_t * e);
extern lv_obj_t * ui_ON2;
extern lv_obj_t * ui_on2test;
void ui_event_OFF2(lv_event_t * e);
extern lv_obj_t * ui_OFF2;
extern lv_obj_t * ui_off2test;
extern lv_obj_t * ui_OUT4;
extern lv_obj_t * ui_out4;
void ui_event_ON4(lv_event_t * e);
extern lv_obj_t * ui_ON4;
extern lv_obj_t * ui_on4test;
void ui_event_OFF4(lv_event_t * e);
extern lv_obj_t * ui_OFF4;
extern lv_obj_t * ui_off4test;
void ui_event_PREVIOUS1(lv_event_t * e);
extern lv_obj_t * ui_PREVIOUS1;
extern lv_obj_t * ui_PREVIOUS2;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_arial13);
LV_FONT_DECLARE(ui_font_arial20);
LV_FONT_DECLARE(ui_font_arialceb16);
LV_FONT_DECLARE(ui_font_arial40);
LV_FONT_DECLARE(ui_font_arial16B8);
LV_FONT_DECLARE(ui_font_arial20B8);
LV_FONT_DECLARE(ui_font_arial30B8);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
