// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project1

//#include "ui.h"
//
//void OUT1_ON(lv_event_t * e)
//{
//	// Your code here
//}
//
//void OUT1_OFF(lv_event_t * e)
//{
//	// Your code here
//}
//
//void OUT3_ON(lv_event_t * e)
//{
//	// Your code here
//}
//
//void OUT3_OFF(lv_event_t * e)
//{
//	// Your code here
//}
//
//void OUT2_ON(lv_event_t * e)
//{
//	// Your code here
//}
//
//void OUT2_OFF(lv_event_t * e)
//{
//	// Your code here
//}
//
//void OUT4_ON(lv_event_t * e)
//{
//	// Your code here
//}
//
//void OUT4_OFF(lv_event_t * e)
//{
//	// Your code here
//}
