// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project1

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DIGI_PANEL = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_DIGI_PANEL, 316);
    lv_obj_set_height(ui_DIGI_PANEL, 377);
    lv_obj_set_x(ui_DIGI_PANEL, -175);
    lv_obj_set_y(ui_DIGI_PANEL, 10);
    lv_obj_set_align(ui_DIGI_PANEL, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DIGI_PANEL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DIGI_PANEL, lv_color_hex(0x83C0D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DIGI_PANEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIGI_MAIN_LABEL = lv_label_create(ui_DIGI_PANEL);
    lv_obj_set_width(ui_DIGI_MAIN_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIGI_MAIN_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIGI_MAIN_LABEL, -11);
    lv_obj_set_y(ui_DIGI_MAIN_LABEL, -150);
    lv_obj_set_align(ui_DIGI_MAIN_LABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DIGI_MAIN_LABEL, "DIGITAL INPUTS");
    lv_obj_set_style_text_font(ui_DIGI_MAIN_LABEL, &ui_font_arial20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIGI1 = lv_obj_create(ui_DIGI_PANEL);
    lv_obj_set_width(ui_DIGI1, 255);
    lv_obj_set_height(ui_DIGI1, 50);
    lv_obj_set_x(ui_DIGI1, -4);
    lv_obj_set_y(ui_DIGI1, -96);
    lv_obj_set_align(ui_DIGI1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DIGI1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_digi1 = lv_label_create(ui_DIGI1);
    lv_obj_set_width(ui_digi1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_digi1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_digi1, -53);
    lv_obj_set_y(ui_digi1, 0);
    lv_obj_set_align(ui_digi1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digi1, "Digital Input 1");
    lv_obj_set_style_text_font(ui_digi1, &ui_font_arial16B8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dvalue1 = lv_label_create(ui_DIGI1);
    lv_obj_set_width(ui_Dvalue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dvalue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dvalue1, 72);
    lv_obj_set_y(ui_Dvalue1, 0);
    lv_obj_set_align(ui_Dvalue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dvalue1, "1");
    lv_obj_set_style_text_font(ui_Dvalue1, &ui_font_arial16B8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIGI2 = lv_obj_create(ui_DIGI_PANEL);
    lv_obj_set_width(ui_DIGI2, 255);
    lv_obj_set_height(ui_DIGI2, 50);
    lv_obj_set_x(ui_DIGI2, -4);
    lv_obj_set_y(ui_DIGI2, -20);
    lv_obj_set_align(ui_DIGI2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DIGI2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_digi2 = lv_label_create(ui_DIGI2);
    lv_obj_set_width(ui_digi2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_digi2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_digi2, -53);
    lv_obj_set_y(ui_digi2, 0);
    lv_obj_set_align(ui_digi2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digi2, "Digital Input 2");
    lv_obj_set_style_text_font(ui_digi2, &ui_font_arial16B8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dvalue2 = lv_label_create(ui_DIGI2);
    lv_obj_set_width(ui_Dvalue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dvalue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dvalue2, 72);
    lv_obj_set_y(ui_Dvalue2, 0);
    lv_obj_set_align(ui_Dvalue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dvalue2, "1");
    lv_obj_set_style_text_font(ui_Dvalue2, &ui_font_arial16B8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIGI3 = lv_obj_create(ui_DIGI_PANEL);
    lv_obj_set_width(ui_DIGI3, 255);
    lv_obj_set_height(ui_DIGI3, 50);
    lv_obj_set_x(ui_DIGI3, -4);
    lv_obj_set_y(ui_DIGI3, 56);
    lv_obj_set_align(ui_DIGI3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DIGI3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_digi3 = lv_label_create(ui_DIGI3);
    lv_obj_set_width(ui_digi3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_digi3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_digi3, -53);
    lv_obj_set_y(ui_digi3, 0);
    lv_obj_set_align(ui_digi3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digi3, "Digital Input 3");
    lv_obj_set_style_text_font(ui_digi3, &ui_font_arial16B8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dvalue3 = lv_label_create(ui_DIGI3);
    lv_obj_set_width(ui_Dvalue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dvalue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dvalue3, 72);
    lv_obj_set_y(ui_Dvalue3, 0);
    lv_obj_set_align(ui_Dvalue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dvalue3, "1");
    lv_obj_set_style_text_font(ui_Dvalue3, &ui_font_arial16B8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIGI4 = lv_obj_create(ui_DIGI_PANEL);
    lv_obj_set_width(ui_DIGI4, 255);
    lv_obj_set_height(ui_DIGI4, 50);
    lv_obj_set_x(ui_DIGI4, -4);
    lv_obj_set_y(ui_DIGI4, 130);
    lv_obj_set_align(ui_DIGI4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DIGI4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_digi4 = lv_label_create(ui_DIGI4);
    lv_obj_set_width(ui_digi4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_digi4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_digi4, -53);
    lv_obj_set_y(ui_digi4, 0);
    lv_obj_set_align(ui_digi4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digi4, "Digital Input 4");
    lv_obj_set_style_text_font(ui_digi4, &ui_font_arial16B8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dvalue4 = lv_label_create(ui_DIGI4);
    lv_obj_set_width(ui_Dvalue4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dvalue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dvalue4, 72);
    lv_obj_set_y(ui_Dvalue4, 0);
    lv_obj_set_align(ui_Dvalue4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dvalue4, "1");
    lv_obj_set_style_text_font(ui_Dvalue4, &ui_font_arial16B8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ANA_PANEL = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_ANA_PANEL, 316);
    lv_obj_set_height(ui_ANA_PANEL, 377);
    lv_obj_set_x(ui_ANA_PANEL, 170);
    lv_obj_set_y(ui_ANA_PANEL, 10);
    lv_obj_set_align(ui_ANA_PANEL, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ANA_PANEL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ANA_PANEL, lv_color_hex(0xCAADBF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ANA_PANEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ANA_MAIN_LABEL = lv_label_create(ui_ANA_PANEL);
    lv_obj_set_width(ui_ANA_MAIN_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ANA_MAIN_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ANA_MAIN_LABEL, -6);
    lv_obj_set_y(ui_ANA_MAIN_LABEL, -150);
    lv_obj_set_align(ui_ANA_MAIN_LABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ANA_MAIN_LABEL, "ANALOG INPUTS");
    lv_obj_set_style_text_font(ui_ANA_MAIN_LABEL, &ui_font_arial20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ANA1 = lv_obj_create(ui_ANA_PANEL);
    lv_obj_set_width(ui_ANA1, 255);
    lv_obj_set_height(ui_ANA1, 50);
    lv_obj_set_x(ui_ANA1, -4);
    lv_obj_set_y(ui_ANA1, -96);
    lv_obj_set_align(ui_ANA1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ANA1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ana1 = lv_label_create(ui_ANA1);
    lv_obj_set_width(ui_ana1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ana1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ana1, -53);
    lv_obj_set_y(ui_ana1, 0);
    lv_obj_set_align(ui_ana1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ana1, "Analog Input 1");
    lv_obj_set_style_text_font(ui_ana1, &ui_font_arial16B8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Avalue1 = lv_label_create(ui_ANA1);
    lv_obj_set_width(ui_Avalue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Avalue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Avalue1, 72);
    lv_obj_set_y(ui_Avalue1, 0);
    lv_obj_set_align(ui_Avalue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Avalue1, "0");

    ui_ANA2 = lv_obj_create(ui_ANA_PANEL);
    lv_obj_set_width(ui_ANA2, 255);
    lv_obj_set_height(ui_ANA2, 50);
    lv_obj_set_x(ui_ANA2, -4);
    lv_obj_set_y(ui_ANA2, -20);
    lv_obj_set_align(ui_ANA2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ANA2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ana2 = lv_label_create(ui_ANA2);
    lv_obj_set_width(ui_ana2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ana2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ana2, -53);
    lv_obj_set_y(ui_ana2, 0);
    lv_obj_set_align(ui_ana2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ana2, "Analog Input 2");
    lv_obj_set_style_text_font(ui_ana2, &ui_font_arial16B8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Avalue2 = lv_label_create(ui_ANA2);
    lv_obj_set_width(ui_Avalue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Avalue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Avalue2, 72);
    lv_obj_set_y(ui_Avalue2, 0);
    lv_obj_set_align(ui_Avalue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Avalue2, "0");

    ui_ANA3 = lv_obj_create(ui_ANA_PANEL);
    lv_obj_set_width(ui_ANA3, 255);
    lv_obj_set_height(ui_ANA3, 50);
    lv_obj_set_x(ui_ANA3, -4);
    lv_obj_set_y(ui_ANA3, 56);
    lv_obj_set_align(ui_ANA3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ANA3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Avalue3 = lv_label_create(ui_ANA3);
    lv_obj_set_width(ui_Avalue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Avalue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Avalue3, 72);
    lv_obj_set_y(ui_Avalue3, 0);
    lv_obj_set_align(ui_Avalue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Avalue3, "0");

    ui_ana3 = lv_label_create(ui_ANA3);
    lv_obj_set_width(ui_ana3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ana3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ana3, -53);
    lv_obj_set_y(ui_ana3, 0);
    lv_obj_set_align(ui_ana3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ana3, "Analog Input 3");
    lv_obj_set_style_text_font(ui_ana3, &ui_font_arial16B8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ANA4 = lv_obj_create(ui_ANA_PANEL);
    lv_obj_set_width(ui_ANA4, 255);
    lv_obj_set_height(ui_ANA4, 50);
    lv_obj_set_x(ui_ANA4, -4);
    lv_obj_set_y(ui_ANA4, 130);
    lv_obj_set_align(ui_ANA4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ANA4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ana4 = lv_label_create(ui_ANA4);
    lv_obj_set_width(ui_ana4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ana4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ana4, -53);
    lv_obj_set_y(ui_ana4, 0);
    lv_obj_set_align(ui_ana4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ana4, "Analog Input 4");
    lv_obj_set_style_text_font(ui_ana4, &ui_font_arial16B8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Avalue4 = lv_label_create(ui_ANA4);
    lv_obj_set_width(ui_Avalue4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Avalue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Avalue4, 72);
    lv_obj_set_y(ui_Avalue4, 0);
    lv_obj_set_align(ui_Avalue4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Avalue4, "0");

    ui_INPUT_LABEL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_INPUT_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_INPUT_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_INPUT_LABEL, -4);
    lv_obj_set_y(ui_INPUT_LABEL, -197);
    lv_obj_set_align(ui_INPUT_LABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_INPUT_LABEL, "INPUTS");
    lv_obj_set_style_text_color(ui_INPUT_LABEL, lv_color_hex(0xB16161), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_INPUT_LABEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_INPUT_LABEL, &ui_font_arial40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NEXT1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_NEXT1, 95);
    lv_obj_set_height(ui_NEXT1, 30);
    lv_obj_set_x(ui_NEXT1, 281);
    lv_obj_set_y(ui_NEXT1, 217);
    lv_obj_set_align(ui_NEXT1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NEXT1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NEXT2 = lv_label_create(ui_NEXT1);
    lv_obj_set_width(ui_NEXT2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NEXT2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NEXT2, 0);
    lv_obj_set_y(ui_NEXT2, 2);
    lv_obj_set_align(ui_NEXT2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NEXT2, "NEXT");
    lv_obj_set_style_text_color(ui_NEXT2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NEXT2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NEXT2, &ui_font_arial16B8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_NEXT1, ui_event_NEXT1, LV_EVENT_ALL, NULL);

}
