// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: PROJECT1

#ifndef _PROJECT1_UI_H
#define _PROJECT1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Digi_In;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Digi_1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Digi_2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Digi_3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Digi_4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_arial13);
LV_FONT_DECLARE(ui_font_arial20);
LV_FONT_DECLARE(ui_font_arialceb16);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
